%% ========================================================================
%  Compute_steering_vectors.m
%
%  Description:
%    Computes normalized steering vectors from RSSI measurements of an
%    antenna measured in an anechoic chamber. The steering vectors
%    characterize the antenna's RSSI response across angles and Wi-Fi
%    channels for both ports, forming the calibration matrix used in
%    RSSI-based angle-of-arrival estimation.
%
%  Dataset Structure employed and data generated:
%	04_Anechoic_Chamber/
%	 └── Compute_steering_vectors.m   (this script)
%
% 	Anechoic_chamber_data/
%    ├── LWA/<ch>/
%    │   └── Measurements_Ch<ch>_BW<bw>.txt (input data generated by Acquire_anechoic_digital.m script)
%	 ├── steering_matrix_normalized.mat (output)
%    └── Localization/LWA/ 
%        └── steering_vector_<angle>deg.fig/.png (output)
%
%  Input .txt Format:
%    timestamp, rssi1, rssi2, tx_bitrate, tx_mcs, rx_bitrate, rx_mcs,
%    throughput, channel, bandwidth, angle
%
%  Output Format "steering_matrix_normalized.mat":
%    steering_matrix_normalized : (N_angles x 2*N_channels) matrix
%      Columns: [P2_ch_last ... P2_ch_first, P1_ch_first ... P1_ch_last]
%      Values in dB, normalized (peak = 0 dB per column).
%
%  Authors: [Guillermo Inglés Muñoz, José Antonio López Pastor]
%  Date:    [04/16/2026]
%  License: [CC-BY-4.0]
%  DOI:     [Dataset DOI]
% =========================================================================

clear all;
close all;
clc;

%% ========================================================================
%  PATH CONFIGURATION (automatic, relative to this script)
%  ========================================================================

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

% Script is in:  <root>/Processing/Localization/
root_dir = fullfile(script_dir, '..');

%% ========================================================================
%  CONFIGURATION (MODIFY HERE)
%  ========================================================================

% --- Antenna under test ---
antenna = 'LWA';   % Options: 'LWA'

% --- Bandwidth ---
bandwidth = '80';

% --- Wi-Fi channels (ascending order) ---
channels = [44, 64, 108, 124, 140, 161];

% --- Angular ranges ---
full_angle_range = -95:95;       % 191 points (full turntable sweep)
trim_index     = 6:186;       % Corresponds to -90:90 degrees
angle_list   = full_angle_range(trim_index);

% --- Display settings ---
display_angle = 50;   % Angle (degrees) to visualize as bar chart

% --- Paths ---
data_dir    = fullfile(root_dir, 'Anechoic_chamber_Data', antenna);
results_dir = fullfile(root_dir, 'Anechoic_chamber_Data', 'Localization', antenna);

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

N_channels = length(channels);

fprintf('Antenna         : %s\n', antenna);
fprintf('Data directory  : %s\n', data_dir);
fprintf('Output directory: %s\n', results_dir);
fprintf('Bandwidth       : %s MHz\n', bandwidth);
fprintf('Channels        : %s\n\n', num2str(channels));

%% ========================================================================
%  STEP 1: READ RAW RSSI DATA AND COMPUTE MEAN PER ANGLE
%  ========================================================================

fprintf('--- Step 1: Loading raw RSSI data ---\n');

mean_rssi_port1 = NaN(length(full_angle_range), N_channels);
mean_rssi_port2 = NaN(length(full_angle_range), N_channels);

for ch_idx = 1:N_channels
    ch = channels(ch_idx);

    file_name = sprintf('Measurements_Ch%d_BW%s.txt', ch, bandwidth);
    file_path = fullfile(data_dir, num2str(ch), file_name);

    if ~isfile(file_path)
        warning('File not found: %s. Skipping channel %d.', file_path, ch);
        continue;
    end

    data = readmatrix(file_path);
    fprintf('  Channel %3d: %d samples loaded\n', ch, size(data, 1));

    for a = 1:length(full_angle_range)
        angle_val = full_angle_range(a);
        rows = data(:, 11) == angle_val;
        if any(rows)
            mean_rssi_port1(a, ch_idx) = mean(data(rows, 2));
            mean_rssi_port2(a, ch_idx) = mean(data(rows, 3));
        end
    end
end

fprintf('  Done. Matrix size: %d angles x %d channels\n\n', ...
    length(full_angle_range), N_channels);

%% ========================================================================
%  STEP 2: BUILD AND NORMALIZE STEERING VECTOR MATRIX
%  ========================================================================

fprintf('--- Step 2: Building steering vector matrix ---\n');

% Column order: [Port2_reversed, Port1_forward]
steering_matrix_raw = [fliplr(mean_rssi_port2), mean_rssi_port1];

% Trim to desired angular range
steering_matrix_trimmed = steering_matrix_raw(trim_index, :);

% Normalize: peak = 0 dB per column
N_vectors = size(steering_matrix_trimmed, 2);
normalization_factors = zeros(1, N_vectors);
steering_matrix_normalized = zeros(size(steering_matrix_trimmed));

for v = 1:N_vectors
    normalization_factors(v) = max(steering_matrix_trimmed(:, v));
    steering_matrix_normalized(:, v) = steering_matrix_trimmed(:, v) - normalization_factors(v);
end

% Column labels
column_labels = cell(1, 2 * N_channels);
for k = 1:N_channels
    column_labels{k}              = sprintf('P2-Ch.%d', channels(N_channels - k + 1));
    column_labels{N_channels + k} = sprintf('P1-Ch.%d', channels(k));
end

fprintf('  Steering matrix size: %d angles x %d vectors\n', size(steering_matrix_normalized));
fprintf('  Angular range: [%d, %d] degrees\n', angle_list(1), angle_list(end));
fprintf('  Normalization complete.\n\n');

%% ========================================================================
%  STEP 3: SAVE STEERING MATRIX
%  ========================================================================
mat_dir = fullfile(root_dir, 'Anechoic_chamber_Data');
output_file = fullfile(mat_dir, 'steering_matrix_normalized.mat');
save(output_file, 'steering_matrix_normalized', 'angle_list', ...
     'channels', 'bandwidth', 'column_labels', 'normalization_factors');
fprintf('Steering matrix saved to: %s\n\n', output_file);

%% ========================================================================
%  FIGURE 1: STEERING VECTOR AT SELECTED ANGLE (bar chart)
%  ========================================================================

[angle_found, angle_idx] = ismember(display_angle, angle_list);
if ~angle_found
    [~, angle_idx] = min(abs(angle_list - display_angle));
    display_angle = angle_list(angle_idx);
end

steering_vector = steering_matrix_normalized(angle_idx, :);

fig = figure('Name', sprintf('Steering Vector at %d deg', display_angle), 'Color', 'w');
bar(steering_vector, 'FaceColor', [0.2 0.4 0.8], 'BaseValue', -30);
grid on; ylim([-30 0]);
set(gca, 'XTick', 1:2*N_channels, 'XTickLabel', column_labels, 'FontSize', 14);
xlabel('Port / Wi-Fi Channel', 'FontSize', 16);
ylabel('Normalized Level (dB)', 'FontSize', 16);
title(sprintf('%s - Steering Vector at %d%s', antenna, display_angle, char(176)), 'FontSize', 18);
saveas(fig, fullfile(results_dir, sprintf('steering_vector_%ddeg.fig', display_angle)));
saveas(fig, fullfile(results_dir, sprintf('steering_vector_%ddeg.png', display_angle)));

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('\n=== PROCESSING COMPLETE ===\n');
fprintf('Antenna              : %s\n', antenna);
fprintf('Bandwidth            : %s MHz\n', bandwidth);
fprintf('Channels             : %s\n', num2str(channels));
fprintf('Angular range        : [%d, %d] degrees (%d points)\n', ...
    angle_list(1), angle_list(end), length(angle_list));
fprintf('Steering matrix size : %d x %d\n', size(steering_matrix_normalized));
fprintf('Figures saved to     : %s\n', results_dir);