%% ========================================================================
%  Compute_monopulse_calibration.m
%
%  Description:
%    Processes anechoic chamber digital RSSI measurements for each Wi-Fi
%    channel, computes normalized radiation patterns and monopulse
%    functions (FM). The output calibration data (normalization factors
%    and FM) is used by the indoor monopulse DoA estimation script.
%
%  Dataset Structure:
%    04_Anechoic_Chamber/
%	  └── process_monopulse_calibration.m   (this script)
%    
% 	Anechoic_chamber_data/
%	  ├── Panel/<ch>/
%     │   └── Measurements_Ch<ch>_BW<bw>.mat (input data generated by Acquire_anechoic_digital.m script)
%	  ├── Monopulse_function_CH<ch>_BW<bw>.mat
%	  └── Localization/Panel/
%         └── Monopulse_function_CH<ch>_BW<bw>.fig/.png
%         
%
%  Input .mat Variables (from acquisition):
%    rssi1_mean      : Mean RSSI Port 1 per angle (1 x N_angles)
%    rssi2_mean      : Mean RSSI Port 2 per angle (1 x N_angles)
%    angle_list      : Angular sweep vector (degrees)
%
%  Output .mat Variables (per channel, calibration):
%    factor_neg  : Normalization factor Port 1 (scalar, dBm)
%    factor_pos  : Normalization factor Port 2 (scalar, dBm)
%    rssi1_norm  : Normalized RSSI Port 1 (1 x N_angles, peak = 0 dB)
%    rssi2_norm  : Normalized RSSI Port 2 (1 x N_angles, peak = 0 dB)
%    FM          : Monopulse function (1 x N_angles)
%    angle_list  : Angular sweep vector (degrees)
%    channel     : Channel number
%    bandwidth   : Bandwidth (MHz)
%
%  Authors: [Guillermo Inglés Muñoz, José Antonio López Pastor]
%  Date:    [04/16/2026]
%  License: [CC-BY-4.0]
%  DOI:     [Dataset DOI]
% =========================================================================

clear all;
close all;
clc;

%% ========================================================================
%  PATH CONFIGURATION (automatic, relative to this script)
%  ========================================================================

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

% Script is in:  <root>/Processing/Localization/
root_dir = fullfile(script_dir, '..');

% Add script directory to path (for Dirplot_modified)
addpath(script_dir);

%% ========================================================================
%  CONFIGURATION (MODIFY HERE)
%  ========================================================================

% --- Antenna under test ---
antenna = 'Panel';   % Options:'Panel'

% --- Wi-Fi channels to process (ascending order) ---
channels = [44, 64, 108, 124, 140, 161];


% --- Bandwidth ---
bw = 80;
bw_str = num2str(bw);

% --- Paths ---
data_dir    = fullfile(root_dir, 'Anechoic_chamber_data', antenna);
results_dir = fullfile(root_dir, 'Anechoic_chamber_Data', 'Localization', antenna);

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

N_channels = length(channels);

fprintf('Antenna         : %s\n', antenna);
fprintf('Data directory  : %s\n', data_dir);
fprintf('Output directory: %s\n', results_dir);
fprintf('Bandwidth       : %d MHz\n', bw);
fprintf('Channels        : %s\n\n', num2str(channels));

%% ========================================================================
%  PROCESS EACH CHANNEL
%  ========================================================================

for ch_idx = 1:N_channels
    ch = channels(ch_idx);
    bandwidth = bw;

    fprintf('--- Processing Channel %d (%d/%d) ---\n', ch, ch_idx, N_channels);

    % ------ Load acquisition data ------
    input_name = sprintf('Measurements_Ch%d_BW%d.mat', ch, bw);
    input_path = fullfile(data_dir,num2str(ch), input_name);

    if ~isfile(input_path)
        % Try with bandwidth subfolder 
        input_path = fullfile(data_dir, num2str(ch), input_name);
    end

    if ~isfile(input_path)
        warning('File not found: %s. Skipping channel %d.', input_path, ch);
        continue;
    end

    d = load(input_path);
    rssi1_mean = d.rssi1_mean;
    rssi2_mean = d.rssi2_mean;
    angle_list = d.angle_list;

    fprintf('  Loaded: %d angular points\n', length(angle_list));

    fig_title = sprintf('%s - Ch.%d - BW %d MHz', antenna, ch, bw);


    % =====================================================================
    %  NORMALIZE: peak = 0 dB per port
    % =====================================================================

    factor_neg = max(rssi1_mean);
    factor_pos = max(rssi2_mean);

    rssi1_norm = rssi1_mean - factor_neg;
    rssi2_norm = rssi2_mean - factor_pos;


    % =====================================================================
    %  COMPUTE MONOPULSE FUNCTION
    % =====================================================================

    rssi1_norm_linear = 10.^(rssi1_norm ./ 10);
    rssi2_norm_linear = 10.^(rssi2_norm ./ 10);

    FM = (rssi2_norm_linear - rssi1_norm_linear) ./ (rssi2_norm_linear + rssi1_norm_linear);

    % =====================================================================
    %  FIGURE: MONOPULSE FUNCTION
    % =====================================================================

    fig = figure('Color', 'w');
    plot(angle_list, FM, 'b', 'LineWidth', 2, 'DisplayName', 'FM');
    grid on; box on;
    title([fig_title ' - Monopulse Function']);
    xlabel('Angle (\circ)'); ylabel('Monopulse Value');
    xlim([-90, 90]);
    legend('Location', 'northwest');
    saveas(fig, fullfile(results_dir, sprintf('Monopulse_function_CH%d_BW%d.fig', ch, bw)));
    saveas(fig, fullfile(results_dir, sprintf('Monopulse_function_CH%d_BW%d.png', ch, bw)));
    close(fig);

    % =====================================================================
    %  SAVE CALIBRATION DATA
    % =====================================================================

    channel = ch;
    output_name = sprintf('Monopulse_function_CH%d_BW%d.mat', ch, bw);
    mat_dir = fullfile(root_dir, 'Anechoic_chamber_Data');
    output_path = fullfile(mat_dir, output_name);

    save(output_path, 'factor_neg', 'factor_pos', 'rssi1_norm', 'rssi2_norm', ...
         'FM', 'angle_list', 'channel', 'bandwidth', '-v7.3');end

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('=== CALIBRATION COMPLETE ===\n');
fprintf('Antenna         : %s\n', antenna);
fprintf('Bandwidth       : %d MHz\n', bw);
fprintf('Channels        : %s\n', num2str(channels));
fprintf('Output files    : %s/Monopulse_function_CH<ch>_BW%d.mat\n', results_dir, bw);
fprintf('Figures saved to: %s\n', results_dir);