%% ========================================================================
%  Plot_anechoic_information.m
%
%  Description:
%  Processes digital communication measurement data from antennas
%  measured in an anechoic chamber. Generates polar plots of RSSI,
%  throughput, TX/RX bitrate, and MCS index vs angle for 5 GHz Wi-Fi
%  channels.
% =========================================================================
%
%  Dataset Structure:
%	04_Anechoic_Chamber/
%	 └── Plot_anechoic_information.m   (this script)
%
%    Anechoic_chamber_data/
%    ├── /<Antena>/<ch>/
%    │   └── Measurements_Ch<ch>_BW<bw>.mat (input data generated by Acquire_anechoic_digital.m script)
%    └── Results/<antena>
%        └── figure .fig/.png
%
%  Input .mat Format:
%    rssi1_mean, rssi2_mean, tx_bitrate_mean, tx_mcs_mean,
%    rx_bitrate_mean, rx_mcs_mean, throughput_mean, angle_list
%
%  Authors: [Guillermo Inglés Muñoz, José Antonio López Pastor]
%  Date:    [04/16/2026]
%  License: [CC-BY-4.0]
%  DOI:     [Dataset DOI]
% 
% This code includes a modified version of dirplot.m by Steve Rickman (Rickman, 2014) used for visualization.
% Modifications include graphical adjustments (font size, label positioning, and line width).
% downloaded from MATLAB File Exchange: https://www.mathworks.com/matlabcentral/fileexchange/1251-dirplot
% 
% Copyright (c) 2014, Steve Rickman
% Used under its original license.
% =========================================================================


clear all;
close all;
clc;

%% ========================================================================
%  PATH CONFIGURATION
%  ========================================================================

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

root_dir = fullfile(script_dir, '..');
addpath(script_dir);

%% ========================================================================
%  CONFIGURATION
%  ========================================================================

antenna    = 'LWA';
bandwidths = {'80'};
channels   = [44, 64, 108, 124, 140, 161]; 
frequencies_hz = [5.220e9, 5.320e9, 5.540e9, 5.620e9, 5.700e9, 5.805e9];

smooth_window = 10;

data_dir    = fullfile(root_dir, 'Anechoic_chamber_data/', antenna);
results_dir = fullfile(root_dir, 'Anechoic_chamber_data/Results/', antenna);

if ~exist(results_dir, 'dir'), mkdir(results_dir); end

N_channels = length(channels);
angles     = -90:1:90;

%% ========================================================================
%  COLOR MAP (Red -> Violet)
%  ========================================================================

base_colors = [
    1.0, 0.0, 0.0;  1.0, 0.5, 0.0;  1.0, 1.0, 0.0;  0.678, 1.0, 0.184;
    0.0, 0.39, 0.0;  0.0, 1.0, 1.0;  0.0, 0.0, 1.0;  0.5, 0.0, 0.5];
N_base = size(base_colors, 1);

if N_channels == 1,      color_map = base_colors(1, :);
elseif N_channels == 2,  color_map = [base_colors(1,:); base_colors(end,:)];
elseif N_channels <= N_base
    color_map = base_colors(round(linspace(1, N_base, N_channels)), :);
else
    color_map = interp1(linspace(1, N_channels, N_base), base_colors, 1:N_channels);
end


%% ========================================================================
%  FIGURE 1: RSSI vs Angle (Polar, smoothed)
%  ========================================================================

fig = figure('Name', 'RSSI - Polar Smoothed', 'Color', 'w');
for m = 1:length(bandwidths)
    bw = bandwidths{m};
    for i = 1:N_channels
        d = load_measurements(data_dir, bw, channels(i));
        
        rssi1 = smooth(d.rssi1_mean(6:186), smooth_window).';
        rssi2 = smooth(d.rssi2_mean(6:186), smooth_window).';
        
        rssi1 = rssi1 + abs(max(rssi1));
        rssi2 = rssi2 + abs(max(rssi2));
        h = Dirplot_modified(angles, rssi1, 'b-', [0, -12, 4]); hold on;
        set(h, 'Color', color_map(i,:), 'DisplayName', sprintf('P1 Ch.%d', channels(i)));

        h = Dirplot_modified(angles, rssi2, 'b--', [0, -12, 4]); hold on;
        set(h, 'Color', color_map(i,:), 'DisplayName', sprintf('P2 Ch.%d', channels(i)));
    end
end
title(sprintf('%s - RSSI Polar Smoothed - BW %s MHz', antenna, bandwidths{1}));
legend('Location', 'northwest', 'FontSize', 10);
saveas(fig, fullfile(results_dir, 'RSSI_polar_smoothed.fig'));
saveas(fig, fullfile(results_dir, 'RSSI_polar_smoothed.png'));

%% ========================================================================
%  FIGURE 2: Throughput vs Angle (Polar)
%  ========================================================================

fig = figure('Name', 'Throughput - Polar', 'Color', 'w');
for m = 1:length(bandwidths)
    bw = bandwidths{m};
    for i = 1:N_channels
        d = load_measurements(data_dir, bw, channels(i));
        tp = d.throughput_mean(6:186);

        h = Dirplot_modified(angles, tp, 'b-', [350, 100, 4]); hold on;
        set(h, 'Color', color_map(i,:), 'DisplayName', sprintf('Ch.%d', channels(i)));
    end
end
title(sprintf('%s - Throughput Polar - BW %s MHz', antenna, bandwidths{1}));
legend('Location', 'northwest', 'FontSize', 10);
saveas(fig, fullfile(results_dir, 'Throughput_polar.fig'));
saveas(fig, fullfile(results_dir, 'Throughput_polar.png'));

%% ========================================================================
%  FIGURE 3: TX Bitrate vs Angle (Polar)
%  ========================================================================

fig = figure('Name', 'TX Bitrate - Polar', 'Color', 'w');
for m = 1:length(bandwidths)
    bw = bandwidths{m};
    for i = 1:N_channels
        d = load_measurements(data_dir, bw, channels(i));
        tx_br = smooth(d.tx_bitrate_mean(6:186), smooth_window).';

        h = Dirplot_modified(angles, tx_br, 'b-', [870, 400, 4]); hold on;
        set(h, 'Color', color_map(i,:), 'DisplayName', sprintf('Ch.%d', channels(i)));
    end
end
title(sprintf('%s - TX Bitrate Polar - BW %s MHz', antenna, bandwidths{1}));
legend('Location', 'northwest', 'FontSize', 10);
saveas(fig, fullfile(results_dir, 'TxBitrate_polar.fig'));
saveas(fig, fullfile(results_dir, 'TxBitrate_polar.png'));

%% ========================================================================
%  FIGURE 4: TX MCS vs Angle (Polar)
%  ========================================================================

fig = figure('Name', 'TX MCS - Polar', 'Color', 'w');
for m = 1:length(bandwidths)
    bw = bandwidths{m};
    for i = 1:N_channels
        d = load_measurements(data_dir, bw, channels(i));
        mcs = round(smooth(d.tx_mcs_mean(6:186), smooth_window)).';

        h = Dirplot_modified(angles, mcs, 'b-', [9, 5, 4]); hold on;
        set(h, 'Color', color_map(i,:), 'DisplayName', sprintf('Ch.%d', channels(i)));
    end
end
title(sprintf('%s - TX MCS Polar - BW %s MHz', antenna, bandwidths{1}));
legend('Location', 'northwest', 'FontSize', 10);
saveas(fig, fullfile(results_dir, 'TxMCS_polar.fig'));
saveas(fig, fullfile(results_dir, 'TxMCS_polar.png'));

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('\n=== PROCESSING COMPLETE ===\n');
fprintf('Antenna              : %s\n', antenna);
fprintf('Bandwidths processed : %s\n', strjoin(bandwidths, ', '));
fprintf('Channels processed   : %s\n', ...
    strjoin(arrayfun(@num2str, channels, 'UniformOutput', false), ', '));
fprintf('Figures saved to     : %s\n', results_dir);

%% ========================================================================
%  HELPER: Load measurement file
%  ========================================================================

function d = load_measurements(data_dir, bw, ch)
    fname = sprintf('Measurements_Ch%d_BW%s.mat', ch, bw);
    fpath = fullfile(data_dir, num2str(ch), fname);
    d = load(fpath);
end