%% ========================================================================
%  process_indoor_comparison.m
%
%  Description:
%    Processes indoor Wi-Fi measurements from multiple angular positions
%    for a given antenna type. For each point and channel, reads the
%    per-angle averaged .mat files, computes per-channel averages, and
%    generates comparative figures across all measurement points.
%
%  Dataset Structure employed and data generated:
%	05_Test_Environment/
%	 └── process_indoor_comparison.m   (this script)
%
%  Dataset Structure:
%  Indoor_test_environment_data
%    │   └── <antenna>/<angle_deg>/<ch>/
%    │       └── Measurements_Ch<ch>_BW<bw>.mat (input data generated by Acquire_indoor.m script)
%    └── Coms/<antenna>
%          └── (output figures .fig/png + indoor_comparison_data.mat)


%  Input .mat Variables:
%    rssi1_mean, rssi2_mean, tx_bitrate_mean, tx_mcs_mean,
%    rx_bitrate_mean, rx_mcs_mean, throughput_mean, angle_list
%
%  Authors: [Guillermo Inglés Muñoz, José Antonio López Pastor]
%  Date:    [04/16/2026]
%  License: [CC-BY-4.0]
%  DOI:     [Dataset DOI]
% =========================================================================

clear all;
close all;
clc;

%% ========================================================================
%  PATH CONFIGURATION (automatic, relative to this script)
%  ========================================================================

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

% Script is in:  <root>/Processing/
% root = 03_Indoor_environment/
root_dir = fullfile(script_dir, '..');

%% ========================================================================
%  CONFIGURATION (MODIFY HERE)
%  ========================================================================

% --- Antenna under test ---
antenna = 'Panel';   % Options: 'LWA', 'Monopole', 'Panel'

% --- Measurement points (degrees) ---
measurement_points = [0, 20, -20, 40, -40, 50, -50];

% --- Wi-Fi channels ---
channels = [44, 64, 108, 124, 140, 161];

% --- Bandwidth ---
bandwidth = 80;
bw_str = num2str(bandwidth);

% --- Visual style per measurement point ---
point_styles = struct( ...
    'color',      {[0 0 1], [1 0 0], [1 0 0], [0 0.5 0], [0 0.5 0], [0 0 0], [0 0 0]}, ...
    'line_style', {'-',     '-',     '--',    '-',       '--',      '-',     '--'});
marker_type    = 'o';
line_width_val = 2;

% --- Paths ---
data_dir    = fullfile(root_dir, 'Indoor_test_environment_data', antenna);
results_dir = fullfile(root_dir, 'Indoor_test_environment_data','Coms', antenna);

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

N_points   = length(measurement_points);
N_channels = length(channels);

fprintf('Antenna         : %s\n', antenna);
fprintf('Data directory  : %s\n', data_dir);
fprintf('Output directory: %s\n\n', results_dir);

%% ========================================================================
%  STEP 1: LOAD AND AVERAGE DATA
%  ========================================================================

fprintf('--- Step 1: Loading measurement data ---\n');

rssi1_all      = NaN(N_points, N_channels);
rssi2_all      = NaN(N_points, N_channels);
tx_bitrate_all = NaN(N_points, N_channels);
tx_mcs_all     = NaN(N_points, N_channels);
rx_bitrate_all = NaN(N_points, N_channels);
rx_mcs_all     = NaN(N_points, N_channels);
throughput_all = NaN(N_points, N_channels);

for p = 1:N_points
    pt = measurement_points(p);
    angle_folder = sprintf('%ddeg', pt);

    for c = 1:N_channels
        ch = channels(c);
        mat_name = sprintf('Measurements_Ch%d_BW%d.mat', ch, bandwidth);
        mat_path = fullfile(data_dir, angle_folder,num2str(ch), mat_name);

        if ~isfile(mat_path)
            warning('File not found: %s', mat_path);
            continue;
        end

        d = load(mat_path);
        rssi1_all(p, c)      = mean(d.rssi1_mean);
        rssi2_all(p, c)      = mean(d.rssi2_mean);
        tx_bitrate_all(p, c) = mean(d.tx_bitrate_mean);
        tx_mcs_all(p, c)     = mean(d.tx_mcs_mean);
        rx_bitrate_all(p, c) = mean(d.rx_bitrate_mean);
        rx_mcs_all(p, c)     = mean(d.rx_mcs_mean);
        throughput_all(p, c)  = mean(d.throughput_mean);
    end
    fprintf('  Point %+3d deg: %d channels loaded\n', pt, sum(~isnan(rssi1_all(p,:))));
end
fprintf('  Done.\n\n');

%% ========================================================================
%  STEP 2: BUILD COMBINED RSSI VECTORS
%  ========================================================================

combined_rssi = [fliplr(rssi2_all), rssi1_all];

combined_rssi_norm = combined_rssi;
for col = 1:size(combined_rssi_norm, 2)
    combined_rssi_norm(:, col) = combined_rssi_norm(:, col) - max(combined_rssi_norm(:, col));
end

combined_labels = cell(1, 2*N_channels);
for k = 1:N_channels
    combined_labels{k}              = sprintf('P2-Ch.%d', channels(N_channels - k + 1));
    combined_labels{N_channels + k} = sprintf('P1-Ch.%d', channels(k));
end
combined_x = 1:(2*N_channels);

%% ========================================================================
%  STEP 3: SAVE PROCESSED DATA
%  ========================================================================

save(fullfile(results_dir, 'indoor_comparison_data.mat'), ...
    'measurement_points', 'channels', 'bandwidth', 'antenna', ...
    'rssi1_all', 'rssi2_all', 'tx_bitrate_all', 'tx_mcs_all', ...
    'rx_bitrate_all', 'rx_mcs_all', 'throughput_all', ...
    'combined_rssi', 'combined_rssi_norm', 'combined_labels');
fprintf('Processed data saved.\n\n');


%% ========================================================================
%  FIGURE 2: TX Bitrate vs Channel
%  ========================================================================

fig = figure('Name', 'TX Bitrate Comparison', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(channels, tx_bitrate_all(p, :), 'Marker', marker_type, ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
xlabel('Channel'); ylabel('TX Bitrate (Mbps)');
title(sprintf('%s - TX Bitrate - BW %d MHz', antenna, bandwidth));
xticks(channels); xlim([min(channels) max(channels)]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_tx_bitrate.fig'));
saveas(fig, fullfile(results_dir, 'comparison_tx_bitrate.png'));
close(fig);

%% ========================================================================
%  FIGURE 3: TX MCS vs Channel
%  ========================================================================

fig = figure('Name', 'TX MCS Comparison', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(channels, round(tx_mcs_all(p, :)), 'Marker', marker_type, ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
xlabel('Channel'); ylabel('TX MCS Index');
title(sprintf('%s - TX MCS - BW %d MHz', antenna, bandwidth));
xticks(channels); xlim([min(channels) max(channels)]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_tx_mcs.fig'));
saveas(fig, fullfile(results_dir, 'comparison_tx_mcs.png'));
close(fig);

%% ========================================================================
%  FIGURE 4: RX Bitrate vs Channel
%  ========================================================================

fig = figure('Name', 'RX Bitrate Comparison', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(channels, rx_bitrate_all(p, :), 'Marker', marker_type, ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
xlabel('Channel'); ylabel('RX Bitrate (Mbps)');
title(sprintf('%s - RX Bitrate - BW %d MHz', antenna, bandwidth));
xticks(channels); xlim([min(channels) max(channels)]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_rx_bitrate.fig'));
saveas(fig, fullfile(results_dir, 'comparison_rx_bitrate.png'));
close(fig);

%% ========================================================================
%  FIGURE 5: RX MCS vs Channel
%  ========================================================================

fig = figure('Name', 'RX MCS Comparison', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(channels, round(rx_mcs_all(p, :)), 'Marker', marker_type, ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
xlabel('Channel'); ylabel('RX MCS Index');
title(sprintf('%s - RX MCS - BW %d MHz', antenna, bandwidth));
xticks(channels); xlim([min(channels) max(channels)]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_rx_mcs.fig'));
saveas(fig, fullfile(results_dir, 'comparison_rx_mcs.png'));
close(fig);

%% ========================================================================
%  FIGURE 6: Throughput vs Channel
%  ========================================================================

fig = figure('Name', 'Throughput Comparison', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(channels, throughput_all(p, :), 'Marker', marker_type, ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
xlabel('Channel'); ylabel('Throughput (Mbps)');
title(sprintf('%s - Throughput - BW %d MHz', antenna, bandwidth));
xticks(channels); xlim([min(channels) max(channels)]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_throughput.fig'));
saveas(fig, fullfile(results_dir, 'comparison_throughput.png'));
close(fig);

%% ========================================================================
%  FIGURE 7: Combined RSSI (steering-vector style)
%  ========================================================================

fig = figure('Name', 'Combined RSSI', 'Color', 'w');
hold on; grid on; box on;
for p = 1:N_points
    pt = measurement_points(p);
    plot(combined_x, combined_rssi(p, :), 'o', ...
        'LineWidth', line_width_val, 'Color', point_styles(p).color, ...
        'LineStyle', point_styles(p).line_style, ...
        'MarkerFaceColor', point_styles(p).color, ...
        'DisplayName', sprintf('%+d%s', pt, char(176)));
end
set(gca, 'XTick', combined_x, 'XTickLabel', combined_labels);
xlabel('Port / Wi-Fi Channel'); ylabel('RSSI (dBm)');
title(sprintf('%s - Combined RSSI - BW %d MHz', antenna, bandwidth));
xlim([0.5, 2*N_channels + 0.5]); legend('Location', 'best');
saveas(fig, fullfile(results_dir, 'comparison_rssi_steering.fig'));
saveas(fig, fullfile(results_dir, 'comparison_rssi_steering.png'));
close(fig);

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('\n=== PROCESSING COMPLETE ===\n');
fprintf('Antenna            : %s\n', antenna);
fprintf('Measurement points : %s\n', num2str(measurement_points));
fprintf('Channels           : %s\n', num2str(channels));
fprintf('Bandwidth          : %d MHz\n', bandwidth);
fprintf('Figures saved to   : %s\n', results_dir);