%% ========================================================================
%  process_indoor_antenna_comparison.m
%
%  Description:
%    Compares indoor Wi-Fi performance across three antenna types
%    (LWA, Monopole, Panel) for each measurement angle. For each angle,
%    loads the corresponding .mat file per antenna and channel, reads
%    the single-valued metrics, and generates three grouped bar charts:
%      1) TX MCS Index vs Channel
%      2) TX Bitrate (Mbps) vs Channel
%      3) Throughput (Mbps) vs Channel
%
%  Dataset Structure employed and data generated:
%	05_Test_Environment/
%	 └── process_indoor_antenna_comparison.m   (this script)
%
%  Dataset Structure:
%  Indoor_test_environment_data
%    │   └── <antenna>/<angle_deg>/<ch>/
%    │       └── Measurements_Ch<ch>_BW<bw>.mat (input data generated by Acquire_indoor.m script)
%    └── Coms/Comparision
%          └── output figures .fig/png
%
%  Input .mat Variables (used):
%    tx_bitrate_mean  
%    tx_mcs_mean      
%    throughput_mean  
%
%  Authors: [Your names here]
%  Date:    [Publication date]
%  License: [e.g., CC-BY-4.0]
%  DOI:     [Dataset DOI]
% =========================================================================

clear all;
close all;
clc;

%% ========================================================================
%  PATH CONFIGURATION (automatic, relative to this script)
%  ========================================================================

script_dir = fileparts(mfilename('fullpath'));
if isempty(script_dir)
    script_dir = pwd;
end

% Script is in:  <root>/Processing/
% root = 03_Indoor_environment/
root_dir = fullfile(script_dir, '..');

%% ========================================================================
%  CONFIGURATION (MODIFY HERE)
%  ========================================================================

% --- Antennas to compare ---
antennas = {'LWA', 'Monopole', 'Panel'};

% --- Measurement points (degrees) ---
measurement_points = [0, 20, -20, 40, -40, 50, -50];

% --- Wi-Fi channels ---
channels = [44, 64, 108, 124, 140, 161];

% --- Bandwidth ---
bandwidth = 80;

% --- Visual style per antenna ---
antenna_colors = {[0 0 1], [1 0 0], [0 0 0]};   % Blue, Red, Black

% --- Paths ---
data_dir    = fullfile(root_dir, 'Indoor_test_environment_data');
results_dir = fullfile(root_dir, 'Indoor_test_environment_data', 'Coms', 'Comparison');

if ~exist(results_dir, 'dir')
    mkdir(results_dir);
end

N_antennas = length(antennas);
N_points   = length(measurement_points);
N_channels = length(channels);

fprintf('Antennas        : %s\n', strjoin(antennas, ', '));
fprintf('Data directory  : %s\n', data_dir);
fprintf('Output directory: %s\n\n', results_dir);

%% ========================================================================
%  CHANNEL TICK LABELS
%  ========================================================================

channel_labels = cell(1, N_channels);
for k = 1:N_channels
    channel_labels{k} = sprintf('#%d', channels(k));
end

%% ========================================================================
%  MAIN LOOP: ONE SET OF FIGURES PER MEASUREMENT ANGLE
%  ========================================================================

bar_width = 0.20;
offsets   = (-(N_antennas-1)/2 : (N_antennas-1)/2) * (bar_width + 0.05);
x_base    = 1:N_channels;

for p = 1:N_points
    pt = measurement_points(p);
    angle_folder = sprintf('%ddeg', pt);
    angle_tag    = sprintf('%+ddeg', pt);   % for titles and filenames

    fprintf('--- Processing angle: %s ---\n', angle_tag);

    % --- Load data for this angle -----------------------------------------
    tx_mcs_data     = NaN(N_antennas, N_channels);
    tx_bitrate_data = NaN(N_antennas, N_channels);
    throughput_data  = NaN(N_antennas, N_channels);

    for a = 1:N_antennas
        ant = antennas{a};
        for c = 1:N_channels
            ch = channels(c);
            mat_name = sprintf('Measurements_Ch%d_BW%d.mat', ch, bandwidth);
            mat_path = fullfile(data_dir, ant, angle_folder, ...
                                num2str(ch), mat_name);

            if ~isfile(mat_path)
                warning('File not found: %s', mat_path);
                continue;
            end

            d = load(mat_path);
            tx_mcs_data(a, c)     = d.tx_mcs_mean;
            tx_bitrate_data(a, c) = d.tx_bitrate_mean;
            throughput_data(a, c)  = d.throughput_mean;
        end
        fprintf('  %s: %d channels loaded\n', ant, sum(~isnan(tx_mcs_data(a,:))));
    end

    % === FIGURE 1: TX MCS vs Channel =====================================
    fig = figure('Name', sprintf('TX MCS %s', angle_tag), 'Color', 'w');
    hold on; grid on; box on;

    for a = 1:N_antennas
        bar(x_base + offsets(a), round(tx_mcs_data(a, :)), bar_width, ...
            'FaceColor', 'none', ...
            'EdgeColor', antenna_colors{a}, ...
            'LineWidth', 1.5, ...
            'DisplayName', antennas{a});
    end

    set(gca, 'XTick', x_base, 'XTickLabel', channel_labels);
    xlim([0.5, N_channels + 0.5]);
    xlabel('channel'); ylabel('MCS');
    legend('Location', 'best');
    hold off;

    saveas(fig, fullfile(results_dir, sprintf('comparison_tx_mcs_%s.fig', angle_tag)));
    saveas(fig, fullfile(results_dir, sprintf('comparison_tx_mcs_%s.png', angle_tag)));
    close(fig);

    % === FIGURE 2: TX Bitrate vs Channel =================================
    fig = figure('Name', sprintf('TX Bitrate %s', angle_tag), 'Color', 'w');
    hold on; grid on; box on;

    for a = 1:N_antennas
        bar(x_base + offsets(a), tx_bitrate_data(a, :), bar_width, ...
            'FaceColor', antenna_colors{a}, ...
            'EdgeColor', [0 0 0], ...
            'LineWidth', 1.5, ...
            'DisplayName', antennas{a});
    end

    set(gca, 'XTick', x_base, 'XTickLabel', channel_labels);
    xlim([0.5, N_channels + 0.5]);
    xlabel('channel'); ylabel('Bitrate (Mbps)');
    legend('Location', 'best');
    hold off;

    saveas(fig, fullfile(results_dir, sprintf('comparison_tx_bitrate_%s.fig', angle_tag)));
    saveas(fig, fullfile(results_dir, sprintf('comparison_tx_bitrate_%s.png', angle_tag)));
    close(fig);

    % === FIGURE 3: Throughput vs Channel =================================
    fig = figure('Name', sprintf('Throughput %s', angle_tag), 'Color', 'w');
    hold on; grid on; box on;

    for a = 1:N_antennas
        bar(x_base + offsets(a), throughput_data(a, :), bar_width, ...
            'FaceColor', antenna_colors{a}, ...
            'EdgeColor', [0 0 0], ...
            'LineWidth', 1.5, ...
            'DisplayName', antennas{a});
    end

    set(gca, 'XTick', x_base, 'XTickLabel', channel_labels);
    xlim([0.5, N_channels + 0.5]);
    xlabel('channel'); ylabel('Throughput (Mbps)');
    legend('Location', 'best');
    hold off;

    saveas(fig, fullfile(results_dir, sprintf('comparison_throughput_%s.fig', angle_tag)));
    saveas(fig, fullfile(results_dir, sprintf('comparison_throughput_%s.png', angle_tag)));
    close(fig);

    fprintf('  Figures saved for %s\n\n', angle_tag);
end

%% ========================================================================
%  SUMMARY
%  ========================================================================

fprintf('\n=== PROCESSING COMPLETE ===\n');
fprintf('Antennas           : %s\n', strjoin(antennas, ', '));
fprintf('Channels           : %s\n', num2str(channels));
fprintf('Bandwidth          : %d MHz\n', bandwidth);
fprintf('Measurement points : %s\n', num2str(measurement_points));
fprintf('Total figures      : %d (3 per angle x %d angles)\n', 3*N_points, N_points);
fprintf('Figures saved to   : %s\n', results_dir);